// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "graphctrl.h"

/////////////////////////////////////////////////////////////////////////////
// CGraphCtrl

IMPLEMENT_DYNCREATE(CGraphCtrl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGraphCtrl properties

short CGraphCtrl::GetTops()
{
	short result;
	GetProperty(0x1, VT_I2, (void*)&result);
	return result;
}

void CGraphCtrl::SetTops(short propVal)
{
	SetProperty(0x1, VT_I2, propVal);
}

BOOL CGraphCtrl::GetOriented()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CGraphCtrl::SetOriented(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CGraphCtrl operations

void CGraphCtrl::SetEdge(long v1, long v2)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 v1, v2);
}

void CGraphCtrl::RemoveEdge(short v1, short v2)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 v1, v2);
}

void CGraphCtrl::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
