Unit _Const;

Interface

 { ---=== Команды ===--- }
  Const
    cmAbout              = $1100;
    cmMatrixCreateDialog = $1101;
    cmMatrixCreate       = $1102;
    cmMatrixEditDialog   = $1103;
    cmMatrixDecE         = $1104;
    cmMatrixTranspon     = $1105;
    cmMatrixStep         = $1106;
    cmMatrixSimm         = $1107;
    cmMatrixCososimm     = $1108;

 { ---=== Помощь ===--- }
  Const
    hcAbout              = $1100;
    hcMatrixCreateDialog = $1101;
    hcMatrixDecE         = $1104;
    hcMatrixTranspon     = $1105;
    hcMatrixStep         = $1106;
    hcMatrixSimm         = $1107;
    hcMatrixCososimm     = $1108;

Implementation

End.
